// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { accountLoginClicked } from "./accountLoginClicked"
import { accountLogoutClicked } from "./accountLogoutClicked"
<<<<<<< HEAD
import { authStateChanged } from "./authStateChanged"
import { fetchUserCreditsData } from "./fetchUserCreditsData"
=======
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d
import { subscribeToAuthCallback } from "./subscribeToAuthCallback"

// Streaming methods for this service
export const streamingMethods = [
  "subscribeToAuthCallback"
]

// Register all account service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("accountLoginClicked", accountLoginClicked)
	registerMethod("accountLogoutClicked", accountLogoutClicked)
<<<<<<< HEAD
	registerMethod("authStateChanged", authStateChanged)
	registerMethod("fetchUserCreditsData", fetchUserCreditsData)
=======
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d
	registerMethod("subscribeToAuthCallback", subscribeToAuthCallback, { isStreaming: true })
}