// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
<<<<<<< HEAD
import { getAvailableTerminalProfiles } from "./getAvailableTerminalProfiles"
=======
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d
import { getLatestState } from "./getLatestState"
import { resetState } from "./resetState"
import { subscribeToState } from "./subscribeToState"
import { toggleFavoriteModel } from "./toggleFavoriteModel"
import { togglePlanActMode } from "./togglePlanActMode"
import { updateAutoApprovalSettings } from "./updateAutoApprovalSettings"
<<<<<<< HEAD
import { updateDefaultTerminalProfile } from "./updateDefaultTerminalProfile"
import { updateSettings } from "./updateSettings"
import { updateTelemetrySetting } from "./updateTelemetrySetting"
import { updateTerminalConnectionTimeout } from "./updateTerminalConnectionTimeout"
import { updateTerminalReuseEnabled } from "./updateTerminalReuseEnabled"
=======
import { updateTerminalConnectionTimeout } from "./updateTerminalConnectionTimeout"
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d

// Streaming methods for this service
export const streamingMethods = [
  "subscribeToState"
]

// Register all state service methods
export function registerAllMethods(): void {
	// Register each method with the registry
<<<<<<< HEAD
	registerMethod("getAvailableTerminalProfiles", getAvailableTerminalProfiles)
=======
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d
	registerMethod("getLatestState", getLatestState)
	registerMethod("resetState", resetState)
	registerMethod("subscribeToState", subscribeToState, { isStreaming: true })
	registerMethod("toggleFavoriteModel", toggleFavoriteModel)
	registerMethod("togglePlanActMode", togglePlanActMode)
	registerMethod("updateAutoApprovalSettings", updateAutoApprovalSettings)
<<<<<<< HEAD
	registerMethod("updateDefaultTerminalProfile", updateDefaultTerminalProfile)
	registerMethod("updateSettings", updateSettings)
	registerMethod("updateTelemetrySetting", updateTelemetrySetting)
	registerMethod("updateTerminalConnectionTimeout", updateTerminalConnectionTimeout)
	registerMethod("updateTerminalReuseEnabled", updateTerminalReuseEnabled)
=======
	registerMethod("updateTerminalConnectionTimeout", updateTerminalConnectionTimeout)
>>>>>>> 16bc1c863785d2e3350bd9c2baa4bc31be43087d
}